package epplib.model.enums;

public enum DomainMessageType {
	FUTURE_FINALIZED, DOMAIN_BLOCKED, DOMAIN_UNBLOCKED, FUTURE_REMOVED, TASTE_REMOVED, DOMAIN_JUDICIAL_REMOVED, DOMAIN_AUTO_RENEWED, DOMAIN_AUTO_RENEW_FAILED
}
